version: '3.8'

services:
  db:
    image: postgres:15-alpine
    platform: linux/arm64
    environment:
      POSTGRES_USER:    dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB:      dev_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      # database.yml でこれら ENV を使うようにしておく
      DATABASE_HOST:     db
      DATABASE_USERNAME: dev
      DATABASE_PASSWORD: password
      DATABASE_NAME:     dev_db
      RAILS_ENV:         development
    depends_on:
      - db
    # サーバ起動前にPID削除＋DB作成・マイグレーション＋Webサーバ起動
    command: >
      bash -lc "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create db:migrate &&
        bundle exec rails s -b 0.0.0.0
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  pgdata:
